config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#dashboard'
  resources :offers do
    resources :orders
  end
  resources :orders, only: [:destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'dashboard', to: 'pages#dashboard'
  get 'favoris', to: 'pages#favoris'
  get 'map', to: 'pages#map'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/offer.rb
class Offer < ApplicationRecord
  belongs_to :user
  has_many :orders, dependent: :destroy
  has_one_attached :image
  validates :brand, :model, :body_type, presence: true
  validates :year, inclusion: { in: (1910..2022) }, numericality: { only_integer: true }
  validates :horsepower, presence: true
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  include PgSearch::Model
  pg_search_scope :search_by_title,
                  against: [:title],
                  using: {
                    tsearch: { prefix: true } # <-- now `superman batm` will return something!
                  }
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :offer
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :offers
  has_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: :home
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  # after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

  def after_sign_in_path_for(resource)
    offers_path
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_action :set_offer, only: [:show, :edit, :update, :destroy]

  def index
    @orders = Order.where(user: current_user)
    @offers = policy_scope(Offer).order(created_at: :desc)
    @offers = @offers.reject { |offer| offer.user_id == current_user.id }
    @demands_reservation = []
    @demands = Order.all
    @demands.select do |demand|
      demand.user_id == current_user.id

      @demands_reservation << demand
    end
    if params[:query].present?
      @offers = Offer.search_by_title(params[:query])
    else
      @offers
    end
  end

  def show
    @order = Order.new
    @demands_reservation = []
    @demands = Order.all
    @demands.select do |demand|
      demand.user_id == current_user.id

      @demands_reservation << demand
    end
    authorize @order
    authorize @offer

  end

  def new
    @offer = Offer.new
    authorize @offer
  end

  def create
    @offer = Offer.new(offer_params)
    @offer.user = current_user
    if @offer.save
      redirect_to offer_path(@offer)
    else
      render :new
    end
    authorize @offer
  end

  def edit
    authorize @offer
  end

  def update
    @offer.update(offer_params)
    redirect_to offer_path
    authorize @offer
  end

  def destroy
    @offer.destroy
    redirect_to offers_path
    authorize @offer
  end

  private

  def set_offer
    @offer = Offer.find(params[:id])
  end

  def offer_params
    params.require(:offer).permit(:title, :price, :brand, :model, :year, :horsepower, :km_age, :body_type, :user_id, :image , :address)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_offer, only: [:index, :new, :create, :show] #[:show, :update, :destroy]
  before_action :set_order, except: [:index, :new, :create] #only:[:show, :update, :destroy]

  def create
    @order = Order.new(order_params)
    @order.offer = @offer
    @order.user = current_user
    if @order.save!
      redirect_to dashboard_path
    else
      render :new
    end
    authorize @order
    #raise
  end

  def index
    # @orders = Order.where(order_id: current_user.id)
    @orders = Order.all
  end

  def new
    @order = Order.new
    authorize @order
  end

  def show
    #@offer = order.offer
    authorize @order
  end

  def edit
    authorize @order
  end

  def update
    @order.status = false
    @user = current_user
    # @order.user = current_user
    @order.save
    redirect_to dashboard_path
    authorize @order
  end

  def destroy
    @order.user = current_user
    @order.destroy
    redirect_to dashboard_path
    authorize @order
  end

  private

  def order_params
    params.require(:order).permit(:offer, :user, :date_start, :date_end)
  end

  def set_order
    @order = Order.find(params[:id])
  end

  def set_offer
    @offer = Offer.find(params[:offer_id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def dashboard
    @user = current_user
    @offers = Offer.where(user: current_user)
    @orders = Order.where(user: current_user)
    @demands_reservation = []
    @demands = Order.all
    @demands.select do |demand|
      demand.user_id == current_user.id
      @demands_reservation << demand
    end
  end

  def favoris
    @offers = Offer.all
  end

  def map
    @offers = Offer.all
    @markers = @offers.geocoded.map do |offer|
      {
        lat: offer.latitude,
        lng: offer.longitude,
        info_window: render_to_string(partial: "info_window", locals: { offer: offer })
      }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rentrocket</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <link rel="manifest" href="<%= asset_path 'manifest.json' %>">
  </head>

  <body>
    <%= yield %>
    <!-- <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p> -->
    <script src="https://code.iconify.design/2/2.2.1/iconify.min.js"></script>
  </body>
</html>

app/views/offers/_form.html.erb
<%= simple_form_for @offer do |f| %>
      <%= f.input :title, placeholder: "Enter the title of your offer"%>
      <%= f.input :price, placeholder: "Enter the price of your offer"%>
      <%= f.input :brand, placeholder: "Enter the car brand"%>
      <%= f.input :model, placeholder: "Enter the car model" %>
      <%= f.input :horsepower,as: :numeric, placeholder: "Enter the car's horsepower" %>
      <%= f.input :year, as: :numeric, placeholder: 'Enter the car year' %>
      <%= f.input :km_age, as: :numeric, placeholder: 'Enter the car kilometrage' %>
      <%= f.input :body_type, as: :numeric,  placeholder: 'Enter the door number' %>
      <%= f.input :color, label: 'Choose the car color', :collection => %w[blue yellow red black]%>
      <%= f.input :image ,label: "Choose your main Image"%>
      <%= f.input :address , placeholder: "Address, City"%>
      <%= f.submit "Create"%>
    <% end %>

app/views/offers/edit.html.erb
<div class="new-offer-view">
  <div class="offer-top">
    <span class="iconify" data-icon="fluent:new-24-filled"></span>
    <h1 class="offer-title">Add a new offer</h1>
  </div>
  <div class="offer-form">
    <%= render 'form', offer: @offer %>
  </div>
<%= link_to 'Back', offers_path %>
</div>

app/views/offers/index.html.erb
<% require 'date' %>
<div class="index">
  <div class="top-section">
    <div class="search-bar-top">
    <h1>Welcome on RentRocket 🚀</h1>
    </div>
    <span id="search-loop" class="iconify" data-icon="bi:search"></span>
    <%= form_tag offers_path, method: :get do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control toto-search",
        placeholder: "Find a car"
      %>
      <%= submit_tag "Search", class: "btn btn-primary" %>
    <% end %>
  </div>
  <% @offers.each do |offer| %>
  <%= link_to offer_path(offer) do%>
  <div class="offer-card">
    <div class="img" style="background-image: url(<%= offer.image.attached? ? cl_image_path(offer.image.key) : asset_path("ferrari.jpg") %>)">
      <span id="favorite" class="iconify" data-icon="bi:heart"></span>
    </div>
    <div class="infos">
      <div class="description">
        <h1 class="model-name"><%= offer.title %></h1>
          <% date = Time.now.day %>
          <% offer_date = offer.created_at %>
          <% if offer_date.to_i == date.to_i %>
            <h2 class="new">New *</h2>
          <% else %>
            <h2 class="new"></h2>
          <% end %>
      </div>
        <h3 class="owner"><%= offer.user.name %>, <%= offer.address ? offer.address.split(",").last : ""%> - <%= offer.km_age %>km<br>
        <span id="price"><%= offer.price %>€</span> / day</h3>
    </div>
  </div>
  <% end %>
  <% end %>
  <%= render "shared/navbar" %>
</div>

app/views/offers/new.html.erb
<div class="new-offer-view">
  <div class="back"><%= link_to "Back", offers_path %></div>
  <div class="offer-top">
    <span class="iconify" data-icon="fluent:new-24-filled"></span>
    <h1 class="offer-title">Add a new offer</h1>
  </div>
  <div class="offer-form">
    <%= render "form" %>
  </div>
</div>

app/views/offers/show.html.erb
<div class="show-offer">
  <div class="back"><%= link_to "Back", offers_path %></div>
  <div class="img" style="background-image: url(<%= @offer.image.attached? ? cl_image_path(@offer.image.key) : asset_path("ferrari.jpg") %>)"></div>
  <div class="infos">

    <div class="description">
      <div class="title">
        <h1 class="model-name"><%= @offer.title %></h1>
        <h3 class="owner"><%= @offer.user.name %>, <%= @offer.address ? @offer.address.split(" ").last : ""%> - <%= @offer.km_age %>km<br></h3>
      </div>
    </div>

    <div class="rarity">
      <div class="rarity-text">
        <h4 class="ratity-title">This car is a rare gem.</h4>
        <p class="rarity-p">This model has just been<br> released and is very popular on<br> Rent Rocket.</p>
      </div>
      <span class="iconify" data-icon="fa:diamond"></span>
    </div>

    <div class="country">
      <div class="country-text">
        <h4 class="country-title">Car designed by </h4>
        <p class="country-p"><%= @offer.brand %></p>
      </div>
    </div>

    <div class="options">
      <div class="options-text">
        <h4 class="options-title"><%= @offer.horsepower %>CV ·  <%= @offer.user.name %></h4>
        <p class="options-p"><%= @offer.body_type %> seats</p>
      </div>
    </div>
    <% reserved = @demands_reservation.select {|demand| demand.offer_id == @offer.id} %>
    <% if @offer.user_id != current_user.id && reserved.count == 0%>
      <div class="booking">
        <div class="price">
          <h4 class="price-title"><span id="price-amount"><%= @offer.price %></span> € / day</h4>
        </div>
        <div class="booking-div">
          <div class="book-bouton">
            <%= link_to "book", new_offer_order_path(@offer) %>
          </div>
        </div>
      </div>
    <% elsif reserved.count == 1 && reserved.count == 1%>
    <% demand = @demands[0] %>
    <div class="booking">
        <div class="price">
        <% months = ["Janvier", "Février", "Mars", "Avril", "Mai" , "Juin", "Juillet" , "Aout" , "Septembre", "Octobre", "Novembre", "Décembre"] %>
          <h4 class="price-title">Déjà réservé du <%= demand.date_start.day%> au <%=  demand.date_end.day%> <%= months[demand.date_start.month - 1] %></h4>
        </div>
      </div>
    <% elsif @offer.user_id == current_user.id%>
    <% else %>
    <div class="booking">
        <div class="price">
          <h4 class="price-title">Déjà réservé</h4>
        </div>
      </div>
    <% end %>
    <%= render "shared/reviews" %>
    <% if policy(@offer).update? && policy(@offer).destroy? %>
      <div class="offer-actions-title">
        <h1 class="offer-title">Manage your Offer</h1>
      </div>
      <div class="actions">
        <%= link_to 'Edit', edit_offer_path, class: 'backlink' %>
        <%= link_to "Delete", offer_path(@offer), method: :delete, remote: true, data: { confirm: "Do you want to delete your offer" } %>
      </div>
    <% end %>
  </div>
  <%= link_to "Delete", destroy_user_session_path, method: :delete, remote: true, class: "btn-logout" %>
  <%= render "shared/navbar" %>
</div>

app/views/orders/index.html.erb
<% @orders.each do |order| %>
  <li><%= order.offer.title %> du <%= order.date_start %> au <%= order.date_end %>
    <%= link_to "Annuler", order_path(order), method: :delete, data: { confirm: "Are you sure?" }, class: 'backlink' %></li>
<% end %>

app/views/orders/new.html.erb
<div class="new-order-view">
  <div class="order-top">
    <span class="iconify" data-icon="clarity:date-line"></span>
    <h1 class="order-title">Choose your dates</h1>
  </div>
  <div class="order-form">
    <%= simple_form_for([@offer,@order]) do |f| %>
      <%= f.input :date_start, :label => "Start date"%>
      <%= f.input :date_end, :label => "End date" %>
      <%= f.submit "Submit" %>
    <% end %>
  </div>
</div>

app/views/orders/show.html.erb
<p>
- <%= demand.offer.title %>
Pour <%= demand.user.name %>,
<%= demand.user.email %>,
Du <%= demand.date_start %>
Au <%= demand.date_end %>
<%= link_to "OK",
offer_order_path(demand.offer, demand),
method: :patch
%>
<p>
<%= link_to "NO",
offer_order_path(demand.offer, demand), method: :delete, data: { confirm: "Are you sure?" } %>
<% end %>


<% requests = @demands_reservation.select {|demand| demand.offer_id == offer.id }%>
<%= requests %>

app/views/pages/_info_window.html.erb
<%= link_to offer_path(offer) do%>
    <h2><%= offer.title %></h2>
    <p><%= offer.address %></p>
<% end %>

app/views/pages/dashboard.html.erb
<div class="dashboard-view">
  <div class="dashboard-top">
    <span class="iconify" data-icon="clarity:dashboard-solid"></span>
    <h1>Welcome, <%= @user.name %></h1>
  </div>
  <div class="my-offers">
    <span class="iconify" data-icon="ic:baseline-local-offer"></span>
    <h1>My Offer<%= @offers.count >= 1 ? "s" : "" %><span>&nbsp;(</span><%= @offers.count %></span>)</h1>
  </div>
  <div class="offer-container-dashboard">
    <% @offers.each do |offer| %>
      <div class="dashboard-offer">
        <h1><%= offer.title %></h1>
        <h1><%= offer.price %> / day</h1>
        <div class="img-status">
          <%= link_to offer_path(offer) do %>
            <div class="offer-img" style="background-image: url(<%= offer.image.attached? ? cl_image_path(offer.image.key) : asset_path("ferrari.jpg") %>)"></div>
          <% end %>
          <div class="offer-demands">
            <ul>
              <% requests = @demands.select { |demand| demand.offer_id == offer.id } %>
              <% if requests.count == 0 %>
                <li>No Request yet</li>
              <% else %>
                <% @demands.each do |demand| %>
                  <% requests.each do |request| %>

                    <li><strong>1 request</strong>&nbsp;by&nbsp;<%= request.user.name %></li>
                    <% if demand.status == true %>
                      <%= link_to "Accept",
                                  offer_order_path(demand.offer, demand),
                                  method: :patch
                      %>
                      <%= link_to "Refuse",
                                  offer_order_path(demand.offer, demand),
                                  method: :delete,
                                  data: { confirm: "Are you sure?" } %>
                    <% else %>
                      <li><strong>Réservé du <%= demand.date_start.day %> au <%= demand.date_end.day %> </strong></li>
                    <% end %>
                  <% end %>
                <% end %>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div class="my-offers">
    <span class="iconify" data-icon="wpf:car-rental"></span>
    <h1>My order<%= @demands_reservation.count >= 1 ? "s" : "" %>
      <span>&nbsp;(</span><%= @demands_reservation.count %></span>)</h1>
  </div>
  <% @demands_reservation.each do |demand| %>
    <% offer = demand.offer %>
    <% if demand.offer.user_id != current_user.id %>
      <%= link_to offer_path(offer) do %>
      <div class="demand-img" style="background-image: url(<%= demand.offer.image.attached? ? cl_image_path(demand.offer.image.key) : asset_path("ferrari.jpg") %>)">
        <h1><%= demand.offer.title %></h1>
        <% if demand.status == false %>
          <span class="iconify" data-icon="bi:check"></span>
        <% else %>
          <span class="iconify" data-icon="bxs:hourglass-bottom"></span>
        <% end %>
        <div class="cancel">
        <%= link_to  order_path(demand), method: :delete, data: { confirm: "Are you sure?" }, class: 'backlink' do%>
        <span class="iconify" data-icon="charm:circle-cross"></span>
        <% end %>
        </div>
      </div>
      <% end %>
    <% end %>
  <% end %>
  <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "btn-logout" %>
</div>
<%= render "shared/navbar" %>

app/views/pages/home.html.erb
<div class="home">
  <img id="logo-home" src="<%= asset_path("logo.png") %>" alt="logo">
  <div class="bouton">
    <%= link_to "log in",  new_user_session_path %>
  </div>
</div>

app/views/pages/map.html.erb
<div style="width: 100%; height: 1000px;"
  data-controller="mapbox"
  data-mapbox-markers-value="<%= @markers.to_json %>"
  data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>
<%= render "shared/navbar" %>

app/views/shared/_navbar.html.erb
<div class="navbar">
  <%= link_to  new_offer_path do%>
  <div class="navbar-btn" >
    <span class="iconify" data-icon="fa-solid:car-alt"></span>
    <label>New Offer</label>
  </div>
  <% end %>
  <div class="navbar-btn">
    <span class="iconify" data-icon="bi:heart">favorites</span>
    <label>favorites</label>
  </div>
  <%= link_to offers_path do%>
  <div class="navbar-btn">
    <span class="iconify" data-icon="emojione-monotone:racing-car">cars</span>
    <label>cars</label>
  </div>
  <% end %>
  <%= link_to map_path do %>
  <div class="navbar-btn">
    <span class="iconify" data-icon="akar-icons:map"></span>
    <label>map</label>
  </div>
  <%end%>
  <%= link_to dashboard_path do%>
  <div class="navbar-btn">
    <% if @orders %>
      <% pending = @orders.select {|order| order.status == true} %>
      <% if pending.count == 0 %>
      <% else %>
        <div class="notif">
          <span id="pending" style="color:white;"><%= pending.count%></span>
        </div>
      <% end %>
    <% end %>
    <% if @offers %>
    <% @offers.each do |offer| %>
    <% if @demands_reservation %>
      <% requests = @demands.select {|demand| demand.offer_id == offer.id } %>
      <% if requests.count == 0 %>
      <% else %>
        <div class="notif">
          <span id="reserv"><%= requests.count%></span>
        </div>
      <% end %>
    <% end %>
    <% end %>
    <% end %>
    <span class="iconify" data-icon="clarity:dashboard-solid"></span>
    <label>dashboard</label>
  </div>
  <% end %>
</div>

app/views/shared/_reviews.html.erb
<div class ="container">

  <div class>
  </div>

  <div class = "card-title">
      <img src='https://kitt.lewagon.com/placeholder/users/arthur-littm' class="avatar-large">
      <div class="card-title-infos">
        <p><strong>Carla</strong></p>
        <p>3 days ago.</p>
      </div>
    </div>

    <div class="card-content">
      <p>Lorem ipsum dolor sit amet. Et adipisci voluptas et dolorem architecto eos autem repellat vel dolores distinctio ea perferendis consectetur sit dolor mollitia non velit consequatur. Nam numquam obcaecati qui eveniet deserunt quo internos nobis et minima maiores voluptatem distinctio.</p>
    </div>

    </div>

</div>